[package]
name = "dysprosium-uci"
version = "0.2.1"
edition = "2024"

[dependencies]
chess = { version = "4.0.0", git = "https://github.com/funnsam/chess.git" }
dysprosium = { version = "0.2.1", path = ".." }
