[package]
name = "dysprosium-lichess"
version = "0.1.0"
edition = "2024"

[dependencies]
dychess = { version = "0.1.0", path = "../dychess" }
dysprosium = { version = "0.1.0", path = ".." }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
ureq = "2.12.1"
